# Generated by Django 5.1.6 on 2025-02-11 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_self_ref_code_refcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RefCode',
        ),
    ]
