# Generated by Django 5.1.6 on 2025-02-11 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_refcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='self_ref_code',
            new_name='invite_ref_code',
        ),
    ]
