# Generated by Django 5.1.6 on 2025-02-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_self_ref_code_user_invite_ref_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
